# Generated by Django 3.0.14 on 2022-06-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220620_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('desc', models.CharField(blank=True, max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='about/about')),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'aboutinfos',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('desc', models.CharField(blank=True, max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='blog/meal')),
            ],
            options={
                'verbose_name': 'chef',
                'verbose_name_plural': 'chefs',
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('desc', models.CharField(blank=True, max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='chef/chef')),
            ],
            options={
                'verbose_name': 'chef',
                'verbose_name_plural': 'chefs',
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('desc', models.CharField(blank=True, max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='slider/slide')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('desc', models.CharField(blank=True, max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='meal/meal')),
                ('cinsi', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'meal',
                'verbose_name_plural': 'meal',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
