# Generated by Django 3.0.14 on 2022-06-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
