# Generated by Django 3.0.14 on 2022-06-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20220622_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='accepted',
            field=models.CharField(blank=True, default='iswaiting', max_length=50),
        ),
    ]
